# ============================================================
# EIRA — PDF Maker (Permission Based Only)
# ============================================================

import sys
sys.path.append("C:/EIRA")

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import (SimpleDocTemplate, Paragraph, 
                                 Spacer, Table, TableStyle)
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os

PURPLE = HexColor("#7C3AED")
DARK   = HexColor("#1E1B4B")
GREEN  = HexColor("#059669")
LIGHT  = HexColor("#F5F3FF")
GRAY   = HexColor("#6B7280")
BORDER = HexColor("#E5E7EB")


def create_pdf(title: str, content: str, pdf_type: str = "notes") -> str:
    """Creates PDF only when explicitly called — never auto"""

    os.makedirs("C:/EIRA/data/pdfs", exist_ok=True)
    date     = datetime.now().strftime("%Y-%m-%d_%H-%M")
    filename = f"C:/EIRA/data/pdfs/{title[:30].replace(' ','_')}_{date}.pdf"

    doc = SimpleDocTemplate(
        filename, pagesize=A4,
        rightMargin=50, leftMargin=50,
        topMargin=50, bottomMargin=50
    )

    story = []

    title_s = ParagraphStyle("T", fontSize=22, textColor=white,
        fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=6)
    sub_s   = ParagraphStyle("S", fontSize=11,
        textColor=HexColor("#C4B5FD"), fontName="Helvetica",
        alignment=TA_CENTER)
    h2_s    = ParagraphStyle("H2", fontSize=14, textColor=PURPLE,
        fontName="Helvetica-Bold", spaceBefore=12, spaceAfter=6)
    body_s  = ParagraphStyle("B", fontSize=10, textColor=DARK,
        fontName="Helvetica", leading=16)
    bull_s  = ParagraphStyle("BL", fontSize=10, textColor=DARK,
        fontName="Helvetica", leading=16, leftIndent=15)

    # Header
    header = Table([
        [Paragraph(title, title_s)],
        [Paragraph(
            f"Created by EIRA • {datetime.now().strftime('%d %B %Y')}",
            sub_s)],
        [Paragraph(f"Type: {pdf_type.upper()}", sub_s)],
    ], colWidths=[480])
    header.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), DARK),
        ("TOPPADDING",    (0,0),(-1,-1), 16),
        ("BOTTOMPADDING", (0,0),(-1,-1), 16),
        ("LEFTPADDING",   (0,0),(-1,-1), 16),
        ("RIGHTPADDING",  (0,0),(-1,-1), 16),
        ("ROUNDEDCORNERS",[8]),
    ]))
    story.append(header)
    story.append(Spacer(1, 20))

    # Parse content
    for line in content.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("## ") or line.startswith("# "):
            story.append(Paragraph(
                line.lstrip("#").strip(), h2_s))
        elif line.startswith("- ") or line.startswith("* "):
            story.append(Paragraph(
                f'<font color="#7C3AED">•</font>  {line[2:]}',
                bull_s))
        elif line[0].isdigit() and ". " in line:
            story.append(Paragraph(
                f'<font color="#059669">→</font>  {line}',
                bull_s))
        else:
            story.append(Paragraph(line, body_s))

    # Footer
    story.append(Spacer(1, 30))
    ft = Table([[Paragraph("Generated by EIRA AI",
        ParagraphStyle("F", fontSize=9, textColor=GRAY,
        fontName="Helvetica", alignment=TA_CENTER))]],
        colWidths=[480])
    ft.setStyle(TableStyle([
        ("LINEABOVE",     (0,0),(-1,-1), 0.5, BORDER),
        ("TOPPADDING",    (0,0),(-1,-1), 8),
        ("BOTTOMPADDING", (0,0),(-1,-1), 8),
    ]))
    story.append(ft)

    doc.build(story)
    return filename


def notes_to_pdf(title: str, content: str) -> str:
    return create_pdf(title, content, "notes")

def plan_to_pdf(title: str, content: str) -> str:
    return create_pdf(title, content, "plan")

def research_to_pdf(title: str, content: str) -> str:
    return create_pdf(title, content, "research")


if __name__ == "__main__":
    path = create_pdf("Test Notes", """
# Binary Search
## What is it?
- Searches sorted array
- Divides array in half each time
## Complexity
- Time: O(log n)
- Space: O(1)
""", "notes")
    print(f"PDF created: {path}")
    import subprocess
    subprocess.Popen(["start", path], shell=True)